import sys
import os
import json
import logging

# Ensure root directory is in sys.path
ROOT_DIR = os.path.abspath(os.path.dirname(__file__))
sys.path.insert(0, ROOT_DIR)

# Mute noisy logging
logging.getLogger("httpx").setLevel(logging.WARNING)

from fastapi.testclient import TestClient
from patentmind.api.main import app

def run_demo():
    print("=" * 60)
    print(" PatentMind AI Phase 8 — Live Demo & Verification Run")
    print("=" * 60)
    
    client = TestClient(app)

    report_lines = []
    report_lines.append("# PatentMind AI Phase 8 — Live Demo Verification Report\n")
    report_lines.append(f"This report was automatically generated by running `python run_demo.py`.\n")

    # 1. System Health Check
    print("\n[1] Fetching System Status...")
    status_resp = client.get("/api/system-status")
    status_data = status_resp.json()
    print("System Status:", json.dumps(status_data, indent=2))
    
    report_lines.append("## 🖥️ 1. System Status & Health Indicators")
    report_lines.append("```json")
    report_lines.append(json.dumps(status_data, indent=2))
    report_lines.append("```\n")

    # 2. Patent Stats
    print("\n[2] Fetching Patent Statistics...")
    stats_resp = client.get("/api/stats")
    stats_data = stats_resp.json()
    total_patents = stats_data.get('total_patents')
    print(f"Total Patents Indexed: {total_patents}")
    print(f"Source Breakdown: {stats_data.get('source_breakdown')}")
    print(f"Status Breakdown: {stats_data.get('status_breakdown')}")
    print(f"Vector Backend: {stats_data.get('vector_backend')}")

    report_lines.append("## 📊 2. Patent Statistics")
    report_lines.append(f"* **Total Patents Indexed:** {total_patents}")
    report_lines.append(f"* **Vector Database Backend:** {stats_data.get('vector_backend')}")
    report_lines.append(f"* **GPU Server Name:** {stats_data.get('gpu_server', 'N/A')}")
    report_lines.append(f"* **Source Distribution:** {json.dumps(stats_data.get('source_breakdown'))}\n")

    # 3. Prescribed Phase 8 Demo Query
    query_text = "What are the most novel methods for training vision transformers on edge devices described in recent AI patents?"
    print(f"\n[3] Running Prescribed Phase 8 Query:\n    \"{query_text}\"\n")

    query_resp = client.post("/api/query", json={"query": query_text})
    if query_resp.status_code != 200:
        print(f"Query Error ({query_resp.status_code}): {query_resp.text}")
        return

    query_data = query_resp.json()
    print("=== LLM RESPONSE ===")
    answer = query_data.get("answer")
    print(answer)
    print("\n=== METADATA ===")
    print(f"Query ID: {query_data.get('query_id')}")
    print(f"LLM Backend Used: {query_data.get('llm_backend_used')}")
    print(f"Vector Backend Used: {query_data.get('vector_backend_used')}")
    print(f"Total Sources Cited: {len(query_data.get('sources', []))}")

    report_lines.append("## 🤖 3. RAG Query & Novelty Answer")
    report_lines.append(f"**Query Prompt:** *\"{query_text}\"*\n")
    report_lines.append("### AI Synthesized Answer:")
    report_lines.append(f"{answer}\n")
    
    report_lines.append("### Pipeline Execution Metadata:")
    report_lines.append(f"* **Query ID:** `{query_data.get('query_id')}`")
    report_lines.append(f"* **LLM Backend:** `{query_data.get('llm_backend_used')}`")
    report_lines.append(f"* **Vector Search:** `{query_data.get('vector_backend_used')}`\n")

    if query_data.get("sources"):
        print("\n=== TOP CITED SOURCES ===")
        report_lines.append("### 📚 Grounded Source Citations:")
        for idx, src in enumerate(query_data["sources"][:5], 1):
            pn = src.get('patent_number')
            sec = src.get('section')
            score = src.get('score', 0)
            chunk = src.get('chunk_text', '')
            print(f"  [{idx}] Patent {pn} | Section: {sec} | Score: {score:.2f}")
            print(f"      Excerpt: {chunk[:120]}...")
            
            report_lines.append(f"#### [{idx}] Patent {pn} ({sec}) — Match: {score*100:.1f}%")
            report_lines.append(f"> {chunk}\n")

    print("\n" + "=" * 60)
    print(" Demo Execution Complete - Phase 8 Ready!")
    print("=" * 60)

    # Save report file
    report_path = os.path.join(ROOT_DIR, "demo_report.md")
    with open(report_path, "w", encoding="utf-8") as f:
        f.write("\n".join(report_lines))
    print(f"\n[+] Success: Exported complete demo results to: {report_path}")

if __name__ == "__main__":
    run_demo()
