"""Initial migration

Revision ID: 02824d5c3a5f
Revises: 
Create Date: 2026-07-22 01:28:17.195750

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '02824d5c3a5f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('patent_id', sa.String(length=100), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('abstract', sa.Text(), nullable=True),
    sa.Column('inventors', sa.JSON(), nullable=True),
    sa.Column('ipc_codes', sa.JSON(), nullable=True),
    sa.Column('pdf_url', sa.String(length=500), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patents_patent_id'), 'patents', ['patent_id'], unique=True)
    op.create_table('reports',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_query', sa.Text(), nullable=False),
    sa.Column('search_keywords', sa.JSON(), nullable=True),
    sa.Column('novelty_score', sa.Integer(), nullable=True),
    sa.Column('novelty_explanation', sa.Text(), nullable=True),
    sa.Column('prior_art', sa.JSON(), nullable=True),
    sa.Column('technical_entities', sa.JSON(), nullable=True),
    sa.Column('report_data', sa.JSON(), nullable=True),
    sa.Column('approval_status', sa.String(length=50), nullable=False),
    sa.Column('approval_feedback', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('research_papers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('paper_id', sa.String(length=100), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('abstract', sa.Text(), nullable=True),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('authors', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_research_papers_paper_id'), 'research_papers', ['paper_id'], unique=True)
    op.create_table('technical_entities',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('source_id', sa.String(length=100), nullable=False),
    sa.Column('algorithms', sa.JSON(), nullable=True),
    sa.Column('datasets', sa.JSON(), nullable=True),
    sa.Column('frameworks', sa.JSON(), nullable=True),
    sa.Column('inventors', sa.JSON(), nullable=True),
    sa.Column('ipc_codes', sa.JSON(), nullable=True),
    sa.Column('keywords', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_technical_entities_source_id'), 'technical_entities', ['source_id'], unique=False)
    op.create_table('approvals',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('report_id', sa.String(length=36), nullable=False),
    sa.Column('decision', sa.String(length=50), nullable=False),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('approvals')
    op.drop_index(op.f('ix_technical_entities_source_id'), table_name='technical_entities')
    op.drop_table('technical_entities')
    op.drop_index(op.f('ix_research_papers_paper_id'), table_name='research_papers')
    op.drop_table('research_papers')
    op.drop_table('reports')
    op.drop_index(op.f('ix_patents_patent_id'), table_name='patents')
    op.drop_table('patents')
    # ### end Alembic commands ###
